#!/bin/bash

# display script usage information
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  --db-user            Set postgreSQL database user"
    echo "  --db-pass            Set postgreSQL database password"
    echo "  -h, --help           Display this help message"
    exit 1
}

# Prompt user and store result in a provided environment variable
get_input() {
    local prompt=$1
    local env_var=$2

    read -p "$prompt" user_input
    if [ -n "$user_input" ]; then
        printf -v "$env_var" "%s" "$user_input"
    else
        echo ${!env_var}
    fi
}

continue_prompt() {
    read -t 15 -p "Do you want to continue? (y/n) [default: y] " yn
    yn=${yn:-y}

    case "$yn" in
        [Yy] ) echo "Continuing...";;
        [Nn] ) echo "Exiting..."; exit 1;;
    esac
}

# Set environment variables
HR=--------------------------------------------------------------------------------
MDL_DIR=~/moodle \
MDL_DATA=/var/www/moodle_data \
PG_USER=moodleuser \
PG_PASS=m@0dlEr
WEB_ROOT=http://moodle.local
ADMIN_USER=admin
ADMIN_PASS=pass

DB_BACKUP_DIR=/var/backups/postgresql
DB_BACKUP_SCRIPT=/usr/local/bin/db_backup
DB_BACKUP_LOG=/var/log/db_backup.log

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --db-user )
            PG_USER="$2"
            shift
            ;;
        --db-pass)
            PG_PASS="$2"
            shift
            ;;
        -h|--help )
            usage
            ;;
        * )
            echo "Unknown option: $1"
            usage
            ;;
    esac
    shift
done

# Get important values from user
if [ ! -f $MDL_DIR/config.php ]; then
    get_input "Enter site url [default: $WEB_ROOT]: " WEB_ROOT
    get_input "Enter admin name [default: $ADMIN_USER]: " ADMIN_USER
    get_input "Enter admin password [default: $ADMIN_PASS]: " ADMIN_PASS
fi

# Set locale info (prevents verbose locale warnings)
if ! cat /etc/locale.gen | tail | grep -w en_CA; then
    echo "LC_ALL=en_CA.UTF-8" | sudo tee -a /etc/environment
    echo "en_CA.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
    echo "LANG=en_CA.UTF-8" | sudo tee -a /etc/locale.conf
    sudo locale-gen en_CA.UTF-8
else
    echo "Skipping setting locale..."
fi

# Install Dependencies
echo -e "$HR\n Installing dependencies...\n$HR"
sudo apt update && sudo apt upgrade -y

if [ ! -f "/etc/apt/sources.list.d/pgdg.list" ]; then
    sudo apt install gpg curl ca-certificates -y
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg # get postgres gpg key
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' # add PostgreSQL apt repository
    sudo apt update -y
fi

sudo apt install -y apache2 postgresql-17 git ufw fail2ban php8.2 php8.2-{curl,dom,gd,intl,mbstring,pgsql,xml,zip}

echo -e "$HR\nDone installing dependencies."
continue_prompt

# Clone Moodle repository
if [ ! -d "$MDL_DIR" ]; then
    echo -e "$HR\n Cloning Moodle repository...\n$HR"
    git clone --depth 1 -b MOODLE_500_STABLE git://git.moodle.org/moodle.git $MDL_DIR
else
    echo "Moodle directory exists. Skipping..."
fi

# Create database
if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw moodle; then
    echo -e "$HR\n Creating Postgres database and Moodle data directory...\n$HR"
    sudo -u postgres psql -U postgres -c "CREATE USER $PG_USER WITH PASSWORD '$PG_PASS'" && sudo -u postgres psql -U postgres -c "CREATE DATABASE moodle WITH OWNER $PG_USER"
else
    echo "Moodle database exists. Skipping..."
fi

# Regular database backups
if ! sudo -u postgres crontab -l 2>/dev/null | grep -q ".*$DB_BACKUP_SCRIPT.*"; then
    echo -e "$HR\n Setting up regular database backups...\n$HR"
    sudo mkdir -p $DB_BACKUP_DIR
    sudo chown postgres:postgres $DB_BACKUP_DIR
    sudo chmod 700 $DB_BACKUP_DIR
    sudo tee "$DB_BACKUP_SCRIPT" << EOF
#!/bin/bash

RETENTION_DAYS=7
TIMESTAMP=\$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="$DB_BACKUP_DIR/moodle_\$TIMESTAMP.sql.gz"

echo "Starting PostgreSQL backup for database: moodle..."
if pg_dump --format=c --file="\$BACKUP_FILE" "moodle"; then
    echo "Backup successful: \$BACKUP_FILE"
    
    echo "Deleting backups older than \$RETENTION_DAYS days..."
    find "$DB_BACKUP_DIR" -type f -name "moodle_*.sql.gz" -mtime +"\$RETENTION_DAYS" -delete
    echo "Old backups cleaned up."
else
    echo "Backup FAILED for database: moodle"
    exit 1
fi
EOF
    sudo chmod +x $DB_BACKUP_SCRIPT
    sudo touch $DB_BACKUP_LOG && sudo chown postgres:postgres $DB_BACKUP_LOG && sudo chmod 640 $DB_BACKUP_LOG
    sudo -u postgres sh -c "echo '0 0 * * 0 $DB_BACKUP_SCRIPT > $DB_BACKUP_LOG 2>&1' | crontab -"
    sudo -u postgres crontab -l
else
    echo "Database backup tasks exists. Skipping..."
fi

# Create moodledata directory
if [ ! -d "$MDL_DATA" ]; then
    sudo mkdir $MDL_DATA && sudo chown -R www-data:www-data $MDL_DATA && sudo chmod 0755 $MDL_DATA
else
    echo "Moodle data directory exists. Skipping..."
fi

# Start Moodle install
if [ ! -f $MDL_DIR/config.php ]; then
    echo -e "$HR\n Running Moodle installer...\n$HR"
    sudo chown -R www-data:www-data $MDL_DIR
    sudo -u www-data php -d max_input_vars=5000 $MDL_DIR/admin/cli/install.php --agree-license --lang=en --wwwroot=$WEB_ROOT --dataroot=$MDL_DATA --dbtype=pgsql --dbuser=$PG_USER --dbpass=$PG_PASS --dbport=5432 --fullname="Rexdale Alliance Church" --shortname="Safe Church" --adminuser=$ADMIN_USER --adminpass=$ADMIN_PASS --non-interactive
    sudo chown -R root:www-data $MDL_DIR && sudo chmod -R 0755 $MDL_DIR $MDL_DATA
else
    echo "Moodle configuration file exists. Skipping..."
fi

echo -e "$HR\nDone creating database.\nDone installing core components."
continue_prompt

# Apache Modules
echo -e "$HR\n Enabling Apache modules...\n$HR"
sudo a2enmod rewrite headers expires rewrite

# Apache PHP Config
echo -e "$HR\n Copying Apache configuration files...\n$HR"
sudo mkdir /var/log/php && sudo chown -R www-data:www-data /var/log/php
sudo mkdir /etc/php/8.2/apache2/conf.d
sudo cp moodle-config/moodle.ini /etc/php/8.2/apache2/conf.d/moodle.ini

# Apache Virtual Host Config
sudo cp moodle-config/moodle.conf /etc/apache2/sites-available/moodle.conf

# Enable Moodle site
echo -e "$HR\n Enabling site...\n$HR"
sudo a2dissite 000-default.conf # disable Apache welcome page
sudo a2ensite moodle.conf # enable moodle site
sudo systemctl reload apache2
sudo systemctl status apache2 --no-pager --lines=0

echo -e "$HR\n Done with Apache configuration."
continue_prompt

# Set up cron service
if ! sudo -u www-data crontab -l 2>/dev/null | grep -q ".*$MDL_DIR/admin/cli/cron.php.*"; then
    echo -e "$HR\n Setting up Moodle cron service...\n$HR"
    sudo -u www-data sh -c "echo '* * * * * /usr/bin/php $MDL_DIR/admin/cli/cron.php >/dev/null' | crontab -"
    sudo -u www-data crontab -l
else
    echo "Moodle cron service exists. Skipping..."
fi

# Set up swapfile
if [ ! -f "/swapfile" ]; then
    echo -e "$HR\n Creating swapfile...\n$HR"
    sudo fallocate -l "$(free -b | awk '/Mem:/ {print $2}')" /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    sudo sh -c "echo '/swapfile none swap sw 0 0' >> /etc/fstab"
    sudo sh -c "echo 'vm.swappiness=20' >> /"
    free -h
else
    echo "Swapfile exists. Skipping..."
fi

# Setup UFW
echo -e "$HR\n Setting up firewall...\n$HR"
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
sudo ufw status verbose

# Setup Fail2Ban
JAIL_CONFIG="/etc/fail2ban/jail.local"
if [ ! -f "$JAIL_CONFIG" ]; then
    echo -e "$HR\n Setting up fail2ban (Brute-force protection)...\n$HR"
    sudo tee "$JAIL_CONFIG" << EOF
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 192.168.16.0/24 192.168.1.0/24 $(curl ifconfig.me)

[sshd]
enabled = true

[apache-auth]
enabled = true

[apache-badbots]
enabled = true

[apache-noscript]
enabled = true

[apache-overflows]
enabled = true
EOF
    sudo systemctl restart fail2ban
    sudo systemctl status fail2ban --no-pager --lines=0
else
    echo "Fail2ban configuration exists. Skipping..."
fi
