#!/bin/bash

# display script usage information
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  --db-user            Set postgreSQL database user"
    echo "  --db-pass            Set postgreSQL database password"
    echo "  -h, --help           Display this help message"
    exit 1
}

# prompt the user and store the result in a provided environment variable
get_input() {
    local prompt=$1
    local env_var=$2

    read -p "$prompt" user_input
    if [ -n "$user_input" ]; then
        printf -v "$env_var" "%s" "$user_input"
    else
        echo ${!env_var}
    fi
}

continue_prompt() {
    read -t 15 -p "Do you want to continue? (y/n) [default: y] " yn
    yn=${yn:-y}

    case "$yn" in
        [Yy] ) echo "Continuing...";;
        [Nn] ) echo "Exiting..."; exit 1;;
    esac
}

# Set environment variables
HR=--------------------------------------------------------------------------------
MDL_DIR=~/moodle \
MDL_DATA=/var/www/moodle_data \
PG_USER=moodleuser \
PG_PASS=m@0dlEr
WEB_ROOT=http://moodle.local
ADMIN_USER=admin
ADMIN_PASS=pass

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --db-user )
            PG_USER="$2"
            shift
            ;;
        --db-pass)
            PG_PASS="$2"
            shift
            ;;
        -h|--help )
            usage
            ;;
        * )
            echo "Unknown option: $1"
            usage
            ;;
    esac
    shift # Shift past the argument name (e.g., -n or --name)
done

# Get important values from user
get_input "Enter site url [default: $WEB_ROOT]: " WEB_ROOT
get_input "Enter admin name [default: $ADMIN_USER]: " ADMIN_USER
get_input "Enter admin password [default: $ADMIN_PASS]: " ADMIN_PASS

# Set locale info (prevents verbose locale warnings)
if ! cat /etc/locale.gen | tail | grep -w en_CA; then
    echo "LC_ALL=en_CA.UTF-8" | sudo tee -a /etc/environment
    echo "en_CA.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
    echo "LANG=en_CA.UTF-8" | sudo tee -a /etc/locale.conf
    sudo locale-gen en_CA.UTF-8
else
    echo "Skipping setting locale..."
fi

# Install Dependencies
echo -e "$HR\n Installing dependencies...\n$HR"
sudo apt update && sudo apt upgrade -y && sudo apt install -y vim apache2 postgresql git php8.2 php8.2-{curl,dom,gd,intl,mbstring,pgsql,xml,zip}
# double check these php modules: json, pcre, xmlrpc

echo -e "$HR\nDone installing dependencies."
continue_prompt

# Clone Moodle repository
if [ ! -d "$MDL_DIR" ]; then
    echo -e "$HR\n Cloning Moodle repository...\n$HR"
    git clone --depth 1 -b MOODLE_500_STABLE git://git.moodle.org/moodle.git $MDL_DIR
else
    echo "Moodle directory exists. Skipping..."
fi

# Create database
if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw moodle; then
    echo -e "$HR\n Creating Postgres database and Moodle data directory...\n$HR"
    sudo -u postgres psql -U postgres -c "CREATE USER $PG_USER WITH PASSWORD '$PG_PASS'" && sudo -u postgres psql -U postgres -c "CREATE DATABASE moodle WITH OWNER $PG_USER"
else
    echo "Moodle database exists. Skipping..."
fi

# Create moodledata directory
if [ ! -d "$MDL_DATA" ]; then
    sudo mkdir $MDL_DATA && sudo chown -R www-data:www-data $MDL_DATA && sudo chmod 0755 $MDL_DATA
else
    echo "Moodle data directory exists. Skipping..."
fi

# Start Moodle install
if [ ! -f $MDL_DIR/config.php ]; then
    echo -e "$HR\n Running Moodle installer...\n$HR"
    sudo chown -R www-data:www-data $MDL_DIR
    sudo -u www-data php -d max_input_vars=5000 $MDL_DIR/admin/cli/install.php --agree-license --lang=en --wwwroot=$WEB_ROOT --dataroot=$MDL_DATA --dbtype=pgsql --dbuser=$PG_USER --dbpass=$PG_PASS --dbport=5432 --fullname="Rexdale Alliance Church" --shortname="Safe Church" --adminuser=$ADMIN_USER --adminpass=$ADMIN_PASS --non-interactive
    sudo chown -R root:www-data $MDL_DIR && sudo chmod -R 0755 $MDL_DIR $MDL_DATA
else
    echo "Moodle configuration file exists. Skipping..."
fi

echo -e "$HR\nDone creating database.\nDone installing core components."
continue_prompt

# Apache Modules
echo -e "$HR\n Enabling Apache modules...\n$HR"
sudo a2enmod rewrite headers expires rewrite

# Apache PHP Config
echo -e "$HR\n Copying Apache configuration files...\n$HR"
sudo mkdir /var/log/php && sudo chown -R www-data:www-data /var/log/php
sudo mkdir /etc/php/8.2/apache2/conf.d
sudo cp moodle-config/moodle.ini /etc/php/8.2/apache2/conf.d/moodle.ini

# Apache Virtual Host Config
sudo cp moodle-config/moodle.conf /etc/apache2/sites-available/moodle.conf

# Enable Moodle site
echo -e "$HR\n Enabling site...\n$HR"
sudo a2dissite 000-default.conf # disable Apache welcome page
sudo a2ensite moodle.conf # enable moodle site
sudo systemctl reload apache2
sudo systemctl status apache2 --no-pager --lines=0
