#!/bin/bash

# display script usage information
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  --db-user            Set postgreSQL database user"
    echo "  --db-pass            Set postgreSQL database password"
    echo "  -h, --help           Display this help message"
    exit 1
}

# Prompt user and store result in a provided environment variable
get_input() {
    local prompt=$1
    local env_var=$2

    read -p "$prompt" user_input
    if [ -n "$user_input" ]; then
        printf -v "$env_var" "%s" "$user_input"
    else
        echo "Using default: ${!env_var}"
    fi
}

continue_prompt() {
    read -t 20 -p "Do you want to continue? (y/n) [default: y] " yn
    yn=${yn:-y}

    case "$yn" in
        [Yy] ) echo "Continuing...";;
        [Nn] ) echo "Exiting..."; exit 1;;
    esac
}

normalize_url() {
    local normalized
    normalized=$(echo "$1" | sed -E 's/^(http|https):\/\///')
    normalized=$(echo "$normalized" | sed -E 's/^www\.//')
    normalized=$(echo "$normalized" | sed -E 's/\/$//')
    echo "$normalized"
}

# Set environment variables
DB_USER=moodleuser
DB_PASS=m@0dlEr
WEB_ROOT=moodle.local
ADMIN_USER=admin
ADMIN_PASS=pass
SITE_NAME="Moodle Site"
SHORT_NAME="Moodle"

MDL_DIR=~/moodle
MDL_DATA=/var/www/moodle_data
DB_BACKUP_DIR=/var/backups/postgresql
DB_BACKUP_SCRIPT=/usr/local/bin/db_backup
DB_BACKUP_LOG=/var/log/db_backup.log
HR=--------------------------------------------------------------------------------

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --db-user )
            DB_USER="$2"
            shift
            ;;
        --db-pass)
            DB_PASS="$2"
            shift
            ;;
        -h|--help )
            usage
            ;;
        * )
            echo "Unknown option: $1"
            usage
            ;;
    esac
    shift
done

# Get important values from user
if [ ! -f $MDL_DIR/config.php ]; then
    while true; do
        get_input "Enter site url [default: $WEB_ROOT]: " WEB_ROOT
        if echo $WEB_ROOT | grep -Pq '^((http|https)://)?(www\.)?([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(/?)$'; then
            WEB_ROOT=$(normalize_url $WEB_ROOT)
            break
        else
            echo "Error: '$WEB_ROOT' is not a valid root URL."
        fi
    done
    get_input "Enter full site name [default: $SITE_NAME]: " SITE_NAME
    get_input "Enter short site name (1-2 words) [default: $SHORT_NAME]: " SHORT_NAME
    get_input "Enter admin name [default: $ADMIN_USER]: " ADMIN_USER
    get_input "Enter admin password [default: $ADMIN_PASS]: " ADMIN_PASS
fi

# Set locale info (prevents verbose locale warnings)
if ! cat /etc/locale.gen | tail | grep -w en_CA; then
    echo "LC_ALL=en_CA.UTF-8" | sudo tee -a /etc/environment
    echo "en_CA.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
    echo "LANG=en_CA.UTF-8" | sudo tee -a /etc/locale.conf
    sudo locale-gen en_CA.UTF-8
else
    echo "Skipping setting locale..."
fi

# Install Dependencies
echo -e "$HR\n Installing dependencies...\n$HR"
sudo apt update && sudo apt upgrade -y

if [ ! -f "/etc/apt/sources.list.d/pgdg.list" ]; then
    sudo apt install gpg curl ca-certificates -y
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg # get postgres gpg key
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' # add PostgreSQL apt repository
    sudo apt update -y
fi

sudo apt install -y apache2 postgresql-17 git ufw fail2ban php8.2 php8.2-{curl,dom,gd,intl,mbstring,pgsql,xml,zip}

echo -e "$HR\nDone installing dependencies."
continue_prompt

# Clone Moodle repository
if [ ! -d "$MDL_DIR" ]; then
    echo -e "$HR\n Cloning Moodle repository...\n$HR"
    git clone --depth 1 -b MOODLE_500_STABLE git://git.moodle.org/moodle.git $MDL_DIR
else
    echo "Moodle directory exists. Skipping..."
fi

# Create database
if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw moodle; then
    echo -e "$HR\n Creating Postgres database and Moodle data directory...\n$HR"
    sudo -u postgres psql -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS'"
    sudo -u postgres psql -U postgres -c "CREATE DATABASE moodle WITH OWNER $DB_USER"
else
    echo "Moodle database exists. Skipping..."
fi

# Regular database backups
if ! sudo -u postgres crontab -l 2>/dev/null | grep -q ".*$DB_BACKUP_SCRIPT.*"; then
    echo -e "$HR\n Setting up regular database backups...\n$HR"
    sudo mkdir -p $DB_BACKUP_DIR
    sudo chown postgres:postgres $DB_BACKUP_DIR
    sudo chmod 700 $DB_BACKUP_DIR
    echo "Creating script at $DB_BACKUP_SCRIPT:"
    sudo tee "$DB_BACKUP_SCRIPT" << EOF
#!/bin/bash

RETENTION_DAYS=7
TIMESTAMP=\$(date +"%Y%m%d_%H%M%S")
BACKUP_FILE="$DB_BACKUP_DIR/moodle_\$TIMESTAMP.sql.gz"

echo "Starting PostgreSQL backup for database: moodle..."
if pg_dump --format=c --file="\$BACKUP_FILE" "moodle"; then
    echo "Backup successful: \$BACKUP_FILE"
    
    echo "Deleting backups older than \$RETENTION_DAYS days..."
    find "$DB_BACKUP_DIR" -type f -name "moodle_*.sql.gz" -mtime +"\$RETENTION_DAYS" -delete
    echo "Old backups cleaned up."
else
    echo "Backup FAILED for database: moodle"
    exit 1
fi
EOF
    sudo chmod +x $DB_BACKUP_SCRIPT
    sudo touch $DB_BACKUP_LOG && sudo chown postgres:postgres $DB_BACKUP_LOG && sudo chmod 640 $DB_BACKUP_LOG
    sudo -u postgres sh -c "echo '0 0 * * 0 $DB_BACKUP_SCRIPT > $DB_BACKUP_LOG 2>&1' | crontab -"
    echo "Added line to postgres user crontab:"
    sudo -u postgres crontab -l
else
    echo "Database backup tasks exists. Skipping..."
fi

# Create moodledata directory
if [ ! -d "$MDL_DATA" ]; then
    sudo mkdir $MDL_DATA && sudo chown -R www-data:www-data $MDL_DATA && sudo chmod 0755 $MDL_DATA
else
    echo "Moodle data directory exists. Skipping..."
fi

# Start Moodle install
if [ ! -f $MDL_DIR/config.php ]; then
    echo -e "$HR\n Running Moodle installer...\n$HR"
    sudo chown -R www-data:www-data $MDL_DIR
    sudo -u www-data php -d max_input_vars=5000 $MDL_DIR/admin/cli/install.php --agree-license --lang=en --wwwroot="http://$WEB_ROOT" --dataroot=$MDL_DATA --dbtype=pgsql --dbuser="$DB_USER" --dbpass="$DB_PASS" --dbport=5432 --fullname="$SITE_NAME" --shortname="$SHORT_NAME" --adminuser="$ADMIN_USER" --adminpass="$ADMIN_PASS" --non-interactive
    sudo chown -R root:www-data $MDL_DIR && sudo chmod -R 0755 $MDL_DIR $MDL_DATA
else
    echo "Moodle configuration file exists. Skipping..."
fi

echo -e "$HR\nDone creating database and installing core components."
continue_prompt

# Apache Modules
echo -e "$HR\n Enabling Apache modules...\n$HR"
sudo a2enmod rewrite headers expires rewrite

# Apache PHP Config
echo -e "$HR\n Copying Apache configuration files...\n$HR"
sudo mkdir /var/log/php && sudo chown -R www-data:www-data /var/log/php
sudo mkdir /etc/php/8.2/apache2/conf.d
echo "Creating php configuration file at /etc/php/8.2/apache2/conf.d/moodle.ini:"
sudo tee "/etc/php/8.2/apache2/conf.d/moodle.ini" << EOF
; Moodle-specific PHP settings
memory_limit = 512M
max_execution_time = 300
upload_max_filesize = 512M
post_max_size = 512M
max_input_vars = 5000

; Error Reporting
display_errors = Off
log_errors = On
error_log = /var/log/php/php_errors.log

; Session Management
session.save_handler = files
session.save_path = /var/lib/php/sessions
session.auto_start = Off

; File Uploads
file_uploads = On

; OPcache
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 4000
opcache.validate_timestamps = 0
EOF

# Apache Virtual Host Config
APACHE_SITE_CONFIG=/etc/apache2/sites-available/moodle.conf
echo "Creating Apache virtual host configuration file at $APACHE_SITE_CONFIG:"
sudo tee "$APACHE_SITE_CONFIG" << EOF
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName $WEB_ROOT
    ServerAlias www.$WEB_ROOT

    DocumentRoot $MDL_DIR

    <Directory $MDL_DIR>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <Directory $MDL_DATA>
        Require all denied
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/moodle_error.log
    CustomLog \${APACHE_LOG_DIR}/moodle_access.log combined

    Redirect permanent / https://$WEB_ROOT
</VirtualHost>

# Suppress Apache's AH00558 warning
ServerName localhost
EOF

# SSL Certificate
SSL_CERT_DIR=/etc/ssl/local_certs
read -p "Is this a production server? (must have publically accessible domain) (y/n) [default: n] " IS_PROD
IS_PROD={IS_PROD:-n}

case "$yn" in
    [Yy] )
    curl -sSL -o mkcert "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
    sudo chmod +x mkcert && sudo mv mkcert /usr/local/bin/mkcert
    mkcert $WEB_ROOT

    sudo mkdir -p $SSL_CERT_DIR
    sudo cp $WEB_ROOT.pem $SSL_CERT_DIR/moodle_dev.crt
    sudo cp $WEB_ROOT-key.pem $SSL_CERT_DIR/moodle_dev.key
    sudo chmod 600 $SSL_CERT_DIR/moodle_dev.key

    sudo tee -a "$APACHE_SITE_CONFIG" << EOF
<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    ServerName $WEB_ROOT
    ServerAlias $WEB_ROOT

    DocumentRoot $MDL_DIR

    <Directory $MDL_DIR>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <Directory $MDL_DATA>
        Require all denied
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/moodle_error.log
    CustomLog \${APACHE_LOG_DIR}/moodle_access.log combined

    SSLEngine on
    SSLCertificateFile $SSL_CERT_DIR/moodle_dev.crt
    SSLCertificateKeyFile $SSL_CERT_DIR/moodle_dev.key

    SSLProtocol all -SSLv2 -SSLv3
    SSLCipherSuite HIGH:!aNULL:!MD5:!RC4
    SSLHonorCipherOrder on
    SSLCompression off
</VirtualHost>
EOF

    cat << EOF
mkcert certificate is located at: $(mkcert -CAROOT)

To use HTTPS locally, first install the mkcert cli on your machine.
Find instructions at: https://github.com/FiloSottile/mkcert

Then install the certificate locally:
scp [local_username]@[your_vps_ip]:$(mkcert -CAROOT) ~/mkcert-CAROOT
CAROOT=~/mkcert-CAROOT mkcert -install

# Add local domain to list of known hosts
echo "[your_vps_ip] $WEB_ROOT" | /etc/hosts
EOF
    ;;
    [Nn] )
        # setup Certbot certificate here!
    ;;
esac

# Enable Moodle site
echo -e "$HR\n Enabling site...\n$HR"
sudo a2dissite 000-default.conf # disable Apache welcome page
sudo a2ensite moodle.conf # enable moodle site
sudo systemctl reload apache2
sudo systemctl status apache2 --no-pager --lines=0

echo -e "$HR\n Done with Apache configuration."
continue_prompt

# Set up cron service
if ! sudo -u www-data crontab -l 2>/dev/null | grep -q ".*$MDL_DIR/admin/cli/cron.php.*"; then
    echo -e "$HR\n Setting up Moodle cron service...\n$HR"
    sudo -u www-data sh -c "echo '* * * * * /usr/bin/php $MDL_DIR/admin/cli/cron.php >/dev/null' | crontab -"
    echo "Added line to www-data user crontab:"
    sudo -u www-data crontab -l
else
    echo "Moodle cron service exists. Skipping..."
fi

# Set up swapfile
if [ ! -f "/swapfile" ]; then
    echo -e "$HR\n Creating swapfile...\n$HR"
    sudo fallocate -l "$(free -b | awk '/Mem:/ {print $2}')" /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    sudo sh -c "echo '/swapfile none swap sw 0 0' >> /etc/fstab"
    sudo sh -c "echo 'vm.swappiness=20' >> /"
    free -h
else
    echo "Swapfile exists. Skipping..."
fi

# Setup UFW
echo -e "$HR\n Setting up firewall...\n$HR"
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
echo "Allowed connection over ssh, http, and https."
echo "Enabling firewall (may required confirmation)..."
sudo ufw enable
sudo ufw status verbose

# Setup Fail2Ban
JAIL_CONFIG="/etc/fail2ban/jail.local"
if [ ! -f "$JAIL_CONFIG" ]; then
    echo -e "$HR\n Setting up fail2ban (Brute-force protection)...\n$HR"
    echo "Creating fail2ban configuration file at $JAIL_CONFIG:"
    sudo tee "$JAIL_CONFIG" << EOF
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 192.168.16.0/24 192.168.1.0/24 $(curl ifconfig.me)

[sshd]
enabled = true

[apache-auth]
enabled = true

[apache-badbots]
enabled = true

[apache-noscript]
enabled = true

[apache-overflows]
enabled = true
EOF
    sudo systemctl restart fail2ban
    sudo systemctl status fail2ban --no-pager --lines=0
else
    echo "Fail2ban configuration exists. Skipping..."
fi
